# Generated by Django 5.0.1 on 2024-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_closedquestionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedquestionresult',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
